// USER
export const LOGIN_USER = 'LOGIN_USER';

// JOBS
export const RECIEVE_JOBS = 'RECIEVE_JOBS';
export const FETCH_JOBS = 'FETCH_JOBS';

// ORGANIZATIONS
export const ADD_SELECTED_ORGS = 'ADD_SELECTED_ORGS';
export const FILTERED_JOBS_BY_ORGS = 'FILTERED_JOBS_BY_ORGS';
export const UNIQUE_ORGANIZATIONS = 'UNIQUE_ORGANIZATIONS';

// JOB TYPES
export const ADD_SELECTED_JOB_TYPES = 'ADD_SELECTED_JOB_TYPES';
